### ISSUE TITLE
wpa_supplicant.conf -> ignore ssid (of a specific accesspoint) but still have the "catch all"

### ISSUE THREAD

**Issue by dl5rcw** [cozybit/wpa_supplicant-o11s-legacy#19]
Dear all,
I am here in Sonderborg, Denmark, and use the 'catch all' entry along with various other SSIDs+Passwords.

```
network={
    ....
}
# here is my 'catch all' entry that works just fine.
network={
    ssid=""
    key_mgmt=NONE
}
network={
    ssid="Sonderborg WiFi"
    key_mgmt=NONE
    disable=1
}
```

I learned that  when I use the 'catch all' entry, I cannot take advantage of the disable=1 option. However, my device eventually connects to the wrong wifi as Sonderborg WiFi will not work for me. Of course I could disable the 'catch all' and do a static entry for the desired (free) network, but when I move on with my mobile device, I would sure like to have the 'catch all' functionality at the next place again right away.
Do I miss out on some config option or could this be a feature request - to implement something like 'block=1' that correlates with the 'catch all' function... or just take the 'disable=1' function into account for the code used in the 'catch all' ?

**Comment by bcopeland** [comment]
FYI: this github is for a (now defunct) fork of wpa_supplicant that was created to add mesh support.  As the changes of interest are now upstream, I'd advise you report this to the official wpa_supplicant upstream (see mailing list at https://w1.fi/hostapd/).
