### ISSUE TITLE
Hide this repo?

### ISSUE THREAD

**Issue by bcopeland** [cozybit/wpa_supplicant-o11s-legacy#20]
Since all new wpas mesh work is happening upstream, is there value (historical or otherwise) in keeping this repo visible?  We occasionally get drive-bys from people who think it is wpa_supplicant upstream.

**Comment by silverjam** [comment]
I think we'd just need to delete the repo, we don't have the ability to make the repo private anymore.

**Comment by silverjam** [comment]
Or, just rename the repo and update the description to be more obvious that this isn't upstream.

**Comment by bcopeland** [comment]
yeah maybe just tacking on '-old' or something would be good enough...

**Comment by chunyeow** [comment]
Or maybe rename to "-o11s"...

**Comment by jcard0na** [comment]
Done!

Cheers,
